"""Tests for _is_commit_ref helper (v2.17.0 git-revert).

Generated by v2170impl on 2026-07-16 09:26 CST.
"""

import subprocess
from pathlib import Path

from tools._helpers import _is_commit_ref


def _make_repo(tmp: Path) -> Path:
    repo = tmp / "repo"
    repo.mkdir()
    subprocess.run(["git", "init", "-q", "-b", "main", str(repo)], check=True)
    subprocess.run(["git", "-C", str(repo), "config", "user.email", "t@t"], check=True)
    subprocess.run(["git", "-C", str(repo), "config", "user.name", "T"], check=True)
    (repo / "a.txt").write_text("a", encoding="utf-8")
    subprocess.run(["git", "-C", str(repo), "add", "a.txt"], check=True)
    subprocess.run(["git", "-C", str(repo), "commit", "-q", "-m", "init"], check=True)
    return repo


def test_commit_ref_true_for_head(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    assert _is_commit_ref("git", str(repo), "HEAD") is True


def test_commit_ref_true_for_sha(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    sha_result = subprocess.run(
        ["git", "-C", str(repo), "rev-parse", "HEAD"],
        capture_output=True,
        text=True,
        check=True,
    )
    assert _is_commit_ref("git", str(repo), sha_result.stdout.strip()) is True


def test_commit_ref_false_for_nonexistent(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    assert _is_commit_ref("git", str(repo), "nonexistent-branch") is False


def test_commit_ref_false_for_blob_path(tmp_path: Path) -> None:
    """A file path inside the repo is NOT a commit ref."""
    repo = _make_repo(tmp_path)
    assert _is_commit_ref("git", str(repo), "a.txt") is False
