"""Tests for ReasonCode class and _make_envelope factory in tools/webapi/_helpers.py.

PR-1 of the git workflow endpoints design.
Spec: docs/superpowers/specs/2026-06-23-git-stage-untage-commit-log-design.md §3,§4
"""

import ast
from pathlib import Path

from tools.webapi._helpers import ReasonCode, _make_envelope


def test_reason_code_has_all_general_codes():
    """Common preflight failure reasons — used by all 10 endpoints eventually."""
    assert ReasonCode.FEATURE_DISABLED == "feature_disabled"
    assert ReasonCode.NO_PROJECT_LOADED == "no_project_loaded"
    assert ReasonCode.WORKTREE_INVALID == "worktree_invalid"
    assert ReasonCode.DIRECTORY_MISSING == "directory_missing"
    assert ReasonCode.NOT_A_GIT_REPO == "not_a_git_repo"
    assert ReasonCode.GIT_UNAVAILABLE == "git_unavailable"
    assert ReasonCode.GIT_ERROR == "git_error"


def test_reason_code_has_body_param_codes():
    """Body / param validation reasons — used by POST endpoints."""
    assert ReasonCode.INVALID_BODY == "invalid_body"
    assert ReasonCode.INVALID_FILES == "invalid_files"
    assert ReasonCode.INVALID_ALL == "invalid_all"
    assert ReasonCode.EMPTY_MESSAGE == "empty_message"
    assert ReasonCode.MESSAGE_TOO_LONG == "message_too_long"
    assert ReasonCode.INVALID_PARAM == "invalid_param"


def test_reason_code_has_path_scope_codes():
    """File path / scope reasons — used by write endpoints + log path filter."""
    assert ReasonCode.PATH_UNSAFE == "path_unsafe"
    assert ReasonCode.NOTHING_STAGED == "nothing_staged"
    assert ReasonCode.PRE_COMMIT_HOOK_FAILED == "pre_commit_hook_failed"
    assert ReasonCode.EMPTY_REPOSITORY == "empty_repository"


# ──────────────────────────────────────────────────────────────────────
# _make_envelope factory tests
# ──────────────────────────────────────────────────────────────────────


def test_make_envelope_success_shape():
    """success=True 时 data 含 reason=None / stderr='',其它字段透传。"""
    env = _make_envelope(
        success=True,
        elapsed_ms=42,
        staged=True,
        files=["a.py"],
        staged_count=1,
    )
    assert env == {
        "status": "ok",
        "data": {
            "staged": True,
            "files": ["a.py"],
            "staged_count": 1,
            "reason": None,
            "stderr": "",
            "elapsed_ms": 42,
        },
    }


def test_make_envelope_failure_shape():
    """success=False 时 data 含 reason + (可选)stderr。"""
    env = _make_envelope(
        success=False,
        reason="invalid_body",
        elapsed_ms=5,
        staged=False,
    )
    assert env["status"] == "ok"
    assert env["data"]["staged"] is False
    assert env["data"]["reason"] == "invalid_body"
    assert env["data"]["stderr"] == ""
    assert env["data"]["elapsed_ms"] == 5


def test_make_envelope_failure_with_stderr():
    """failure 路径可传 stderr(写端点 hook 失败用)。"""
    env = _make_envelope(
        success=False,
        reason="pre_commit_hook_failed",
        stderr="pre-commit hook failed",
        elapsed_ms=100,
    )
    assert env["data"]["stderr"] == "pre-commit hook failed"


def test_make_envelope_extra_kwargs_pass_through():
    """data 字段 = 透传 kwargs(写端点必传 directory/umo/worktree)。"""
    env = _make_envelope(
        success=True,
        elapsed_ms=10,
        directory="/repo",
        umo="u:m",
        worktree="/repo",
    )
    data = env["data"]
    assert data["directory"] == "/repo"
    assert data["umo"] == "u:m"
    assert data["worktree"] == "/repo"
    assert data["reason"] is None


# ──────────────────────────────────────────────────────────────────────
# v2.14.0 worktree-mgmt 11 新增 ReasonCode 常量
# ──────────────────────────────────────────────────────────────────────


def test_worktree_mgmt_reason_codes_defined():
    """v2.14.0 + 11 new ReasonCode constants for worktree-mgmt endpoints."""
    from tools.webapi._helpers import ReasonCode

    # ADD-specific
    assert ReasonCode.INVALID_BRANCH == "invalid_branch"
    assert ReasonCode.PATH_EXISTS_NONEMPTY == "path_exists_nonempty"
    assert ReasonCode.CANNOT_CREATE_EXISTING == "cannot_create_existing"
    assert ReasonCode.CANNOT_CHECKOUT_MISSING == "cannot_checkout_missing"
    assert ReasonCode.WORKTREE_NOT_IN_REPO == "worktree_not_in_repo"
    # REMOVE / LOCK / UNLOCK
    assert ReasonCode.WORKTREE_NOT_FOUND == "worktree_not_found"
    assert ReasonCode.CANNOT_REMOVE_MAIN == "cannot_remove_main"
    assert ReasonCode.WORKTREE_LOCKED == "worktree_locked"
    assert ReasonCode.WORKTREE_DIRTY == "worktree_dirty"
    assert ReasonCode.ALREADY_LOCKED == "already_locked"
    assert ReasonCode.NOT_LOCKED == "not_locked"


# Generated by v2170impl on 2026-07-16 09:26 CST.
def test_v217_git_reason_codes_defined():
    """v2.17.0 git-init/branch/revert reason codes are centralized."""
    expected = {
        "PATH_NOT_DIRECTORY": "path_not_directory",
        "DIRECTORY_NOT_EMPTY": "directory_not_empty",
        "ALREADY_A_GIT_REPO": "already_a_git_repo",
        "INIT_FAILED": "init_failed",
        "BRANCH_EXISTS": "branch_exists",
        "BRANCH_NOT_FOUND": "branch_not_found",
        "BRANCH_IS_CURRENT": "branch_is_current",
        "BRANCH_NOT_MERGED": "branch_not_merged",
        "WORKTREE_DIRTY": "worktree_dirty",
        "COMMIT_NOT_FOUND": "commit_not_found",
        "REVERT_CONFLICT": "revert_conflict",
        "NOTHING_TO_REVERT": "nothing_to_revert",
    }
    for name, value in expected.items():
        assert getattr(ReasonCode, name) == value


# Generated by v2170impl on 2026-07-16 09:48 CST.
def test_v217_reason_codes_do_not_redeclare_existing_literals() -> None:
    """The v2.17 block must contain only new ReasonCode names."""
    source_path = (
        Path(__file__).resolve().parents[1] / "tools" / "webapi" / "_helpers.py"
    )
    source = source_path.read_text(encoding="utf-8")
    marker_line = next(
        number
        for number, line in enumerate(source.splitlines(), start=1)
        if "v2.17.0 新增:git-init" in line
    )
    tree = ast.parse(source)
    reason_class = next(
        node
        for node in tree.body
        if isinstance(node, ast.ClassDef) and node.name == "ReasonCode"
    )

    names_before_marker: set[str] = set()
    names_in_v217_block: set[str] = set()
    for node in reason_class.body:
        if not isinstance(node, ast.Assign):
            continue
        names = {target.id for target in node.targets if isinstance(target, ast.Name)}
        if node.lineno < marker_line:
            names_before_marker.update(names)
        else:
            names_in_v217_block.update(names)

    assert names_before_marker.isdisjoint(names_in_v217_block)


# ── PR-4 vivado-mcp 8 个新 ReasonCode (2026-07-23) ──


def test_vivado_reason_codes_defined():
    """PR-4 (2026-07-23): 8 new ReasonCode constants for vivado-mcp."""
    assert ReasonCode.VIVADO_NOT_INSTALLED == "vivado_not_installed"
    assert ReasonCode.VIVADO_EXECUTABLE_INVALID == "vivado_executable_invalid"
    assert ReasonCode.MCP_NOT_RUNNING == "mcp_not_running"
    assert ReasonCode.MCP_STARTUP_FAILED == "mcp_startup_failed"
    assert ReasonCode.SESSION_NOT_FOUND == "session_not_found"
    assert ReasonCode.SESSION_ALREADY_EXISTS == "session_already_exists"
    assert ReasonCode.VIVADO_STARTUP_FAILED == "vivado_startup_failed"
    assert ReasonCode.MAX_SESSIONS_REACHED == "max_sessions_reached"
