"""Tests for v2.17.0 git-init shared preflight and stderr classifiers.

Generated by v2170impl on 2026-07-16 09:26 CST.
"""

import asyncio
import subprocess
from collections.abc import Awaitable
from pathlib import Path
from typing import Any

import pytest
from tools.webapi._helpers import (
    ReasonCode,
    _classify_revert_stderr,
    _classify_switch_stderr,
    _git_init_preflight,
)

from tests.conftest import _make_plugin


@pytest.fixture
def plugin() -> Any:
    """Build a per-test plugin using the shared project factory."""
    return _make_plugin()


def _await(
    coro: Awaitable[tuple[dict | None, dict | None]],
) -> tuple[dict | None, dict | None]:
    """Run a preflight coroutine in synchronous tests."""
    return asyncio.run(coro)


def test_init_preflight_happy_path(tmp_path: Path, plugin: Any) -> None:
    target = tmp_path / "new_repo"
    target.mkdir()
    err, ctx = _await(_git_init_preflight(plugin, path=str(target)))
    assert err is None
    assert ctx is not None
    assert ctx["path"] == str(target.resolve())


def test_init_preflight_path_missing(tmp_path: Path, plugin: Any) -> None:
    err, ctx = _await(_git_init_preflight(plugin, path=str(tmp_path / "nope")))
    assert err is not None
    assert ctx is None
    assert err["data"]["reason"] == ReasonCode.PATH_NOT_DIRECTORY


def test_init_preflight_path_is_file(tmp_path: Path, plugin: Any) -> None:
    file_path = tmp_path / "f.txt"
    file_path.write_text("x", encoding="utf-8")
    err, ctx = _await(_git_init_preflight(plugin, path=str(file_path)))
    assert err is not None
    assert ctx is None
    assert err["data"]["reason"] == ReasonCode.PATH_NOT_DIRECTORY


def test_init_preflight_directory_not_empty(
    tmp_path: Path,
    plugin: Any,
) -> None:
    target = tmp_path / "occupied"
    target.mkdir()
    (target / "README.md").write_text("hi", encoding="utf-8")
    err, ctx = _await(_git_init_preflight(plugin, path=str(target)))
    assert err is not None
    assert ctx is None
    assert err["data"]["reason"] == ReasonCode.DIRECTORY_NOT_EMPTY


def test_init_preflight_already_git_repo(tmp_path: Path, plugin: Any) -> None:
    target = tmp_path / "already"
    target.mkdir()
    subprocess.run(["git", "init", "-q", str(target)], check=True)
    err, ctx = _await(_git_init_preflight(plugin, path=str(target)))
    assert err is not None
    assert ctx is None
    assert err["data"]["reason"] == ReasonCode.ALREADY_A_GIT_REPO


def test_init_preflight_path_unsafe_traversal(
    tmp_path: Path,
    plugin: Any,
) -> None:
    del tmp_path
    plugin._config["file_remove_blacklist"] = ["C:/Windows"]
    err, ctx = _await(_git_init_preflight(plugin, path="../../../etc"))
    assert err is not None
    assert ctx is None
    assert err["data"]["reason"] == ReasonCode.PATH_UNSAFE


@pytest.mark.parametrize(
    ("stderr", "expected"),
    [
        ("fatal: a branch named 'feature/x' already exists", ReasonCode.BRANCH_EXISTS),
        (
            "error: pathspec 'missing' did not match any file(s)",
            ReasonCode.BRANCH_NOT_FOUND,
        ),
        (
            "Your local changes would be overwritten by checkout",
            ReasonCode.WORKTREE_DIRTY,
        ),
        ("fatal: 'bad name' is not a valid branch name", ReasonCode.INVALID_BRANCH),
        ("fatal: cannot switch", ReasonCode.GIT_ERROR),
    ],
)
def test_classify_switch_stderr(stderr: str, expected: str) -> None:
    assert _classify_switch_stderr(stderr) == expected


@pytest.mark.parametrize(
    ("stderr", "expected"),
    [
        ("pre-commit hook failed", ReasonCode.HOOK_REJECTED),
        ("Please tell me who you are", ReasonCode.IDENTITY_NOT_SET),
        ("error: nothing to revert", ReasonCode.NOTHING_TO_REVERT),
        ("CONFLICT (content): merge conflict", ReasonCode.REVERT_CONFLICT),
        ("Your local changes would be overwritten", ReasonCode.WORKTREE_DIRTY),
        ("fatal: revert failed", ReasonCode.GIT_ERROR),
    ],
)
def test_classify_revert_stderr(stderr: str, expected: str) -> None:
    assert _classify_revert_stderr(stderr) == expected


# ── v2.17.1: force 标志 ────────────────────────────────────


def test_init_preflight_force_true_skips_nonempty_check(
    tmp_path: Path, plugin: Any
) -> None:
    """force=true 时,非空目录(无 .git)应通过 preflight。"""
    target = tmp_path / "occupied"
    target.mkdir()
    (target / "README.md").write_text("hello", encoding="utf-8")
    err, ctx = _await(_git_init_preflight(plugin, path=str(target), force=True))
    assert err is None
    assert ctx is not None
    assert Path(ctx["path"]).resolve() == target.resolve()


def test_init_preflight_force_false_rejects_nonempty(
    tmp_path: Path, plugin: Any
) -> None:
    """force=false 时,非空目录仍被拒绝。"""
    target = tmp_path / "occupied"
    target.mkdir()
    (target / "README.md").write_text("hello", encoding="utf-8")
    err, ctx = _await(_git_init_preflight(plugin, path=str(target), force=False))
    assert err is not None
    assert err["data"]["reason"] == ReasonCode.DIRECTORY_NOT_EMPTY
    assert ctx is None


def test_init_preflight_force_default_rejects_nonempty(
    tmp_path: Path, plugin: Any
) -> None:
    """不传 force(默认)时,非空目录仍被拒绝 - 向后兼容验证。"""
    target = tmp_path / "occupied"
    target.mkdir()
    (target / "README.md").write_text("hello", encoding="utf-8")
    err, ctx = _await(_git_init_preflight(plugin, path=str(target)))
    assert err is not None
    assert err["data"]["reason"] == ReasonCode.DIRECTORY_NOT_EMPTY


def test_init_preflight_force_true_still_rejects_already_git_repo(
    tmp_path: Path, plugin: Any
) -> None:
    """force=true 时,已有 .git 的目录仍被拒绝(hard-ban)。"""
    target = tmp_path / "already"
    target.mkdir()
    subprocess.run(["git", "init", "-q", str(target)], check=True)
    err, ctx = _await(_git_init_preflight(plugin, path=str(target), force=True))
    assert err is not None
    assert err["data"]["reason"] == ReasonCode.ALREADY_A_GIT_REPO


def test_init_preflight_force_true_still_rejects_path_not_directory(
    tmp_path: Path, plugin: Any
) -> None:
    """force=true 时,不存在的路径仍被拒绝(force 不绕过路径防御)。"""
    err, ctx = _await(
        _git_init_preflight(plugin, path=str(tmp_path / "nope"), force=True)
    )
    assert err is not None
    assert err["data"]["reason"] == ReasonCode.PATH_NOT_DIRECTORY


def test_init_preflight_force_true_still_rejects_path_unsafe(
    plugin: Any,
) -> None:
    """force=true 时,含 .. 的路径仍被拒绝(force 不绕过路径安全)。"""
    err, ctx = _await(_git_init_preflight(plugin, path="../../../etc", force=True))
    assert err is not None
    assert err["data"]["reason"] == ReasonCode.PATH_UNSAFE


def test_init_preflight_force_true_with_subdirectory(
    tmp_path: Path, plugin: Any
) -> None:
    """force=true 时,非空目录(含子目录)也应通过 preflight。"""
    target = tmp_path / "occupied"
    target.mkdir()
    (target / "src").mkdir()
    (target / "src" / "main.py").write_text("print('hi')", encoding="utf-8")
    err, ctx = _await(_git_init_preflight(plugin, path=str(target), force=True))
    assert err is None
    assert ctx is not None
