"""Tests for v2.17.0 git-init shared preflight and stderr classifiers.

Generated by v2170impl on 2026-07-16 09:26 CST.
"""

import asyncio
import subprocess
from collections.abc import Awaitable
from pathlib import Path
from typing import Any
from unittest.mock import MagicMock

import pytest
from tools.webapi._helpers import (
    ReasonCode,
    _classify_revert_stderr,
    _classify_switch_stderr,
    _git_init_preflight,
)


def _make_plugin() -> MagicMock:
    """Create the minimal plugin configuration needed by init preflight."""
    plugin = MagicMock()
    plugin._config = {
        "file_remove_blacklist": None,
        "git_path": "",
    }
    return plugin


@pytest.fixture
def init_plugin() -> Any:
    """Build the init-specific test plugin configuration."""
    return _make_plugin()


def _await(
    coro: Awaitable[tuple[dict | None, dict | None]],
) -> tuple[dict | None, dict | None]:
    """Run a preflight coroutine in synchronous tests."""
    return asyncio.run(coro)


def test_init_preflight_happy_path(tmp_path: Path, init_plugin: Any) -> None:
    target = tmp_path / "new_repo"
    target.mkdir()
    err, ctx = _await(_git_init_preflight(init_plugin, path=str(target)))
    assert err is None
    assert ctx is not None
    assert ctx["path"] == str(target.resolve())


def test_init_preflight_path_missing(tmp_path: Path, init_plugin: Any) -> None:
    err, ctx = _await(_git_init_preflight(init_plugin, path=str(tmp_path / "nope")))
    assert err is not None
    assert ctx is None
    assert err["data"]["reason"] == ReasonCode.PATH_NOT_DIRECTORY


def test_init_preflight_path_is_file(tmp_path: Path, init_plugin: Any) -> None:
    file_path = tmp_path / "f.txt"
    file_path.write_text("x", encoding="utf-8")
    err, ctx = _await(_git_init_preflight(init_plugin, path=str(file_path)))
    assert err is not None
    assert ctx is None
    assert err["data"]["reason"] == ReasonCode.PATH_NOT_DIRECTORY


def test_init_preflight_directory_not_empty(
    tmp_path: Path,
    init_plugin: Any,
) -> None:
    target = tmp_path / "occupied"
    target.mkdir()
    (target / "README.md").write_text("hi", encoding="utf-8")
    err, ctx = _await(_git_init_preflight(init_plugin, path=str(target)))
    assert err is not None
    assert ctx is None
    assert err["data"]["reason"] == ReasonCode.DIRECTORY_NOT_EMPTY


def test_init_preflight_already_git_repo(tmp_path: Path, init_plugin: Any) -> None:
    target = tmp_path / "already"
    target.mkdir()
    subprocess.run(["git", "init", "-q", str(target)], check=True)
    err, ctx = _await(_git_init_preflight(init_plugin, path=str(target)))
    assert err is not None
    assert ctx is None
    assert err["data"]["reason"] == ReasonCode.ALREADY_A_GIT_REPO


def test_init_preflight_path_unsafe_traversal(
    tmp_path: Path,
    init_plugin: Any,
) -> None:
    del tmp_path
    init_plugin._config["file_remove_blacklist"] = ["C:/Windows"]
    err, ctx = _await(_git_init_preflight(init_plugin, path="../../../etc"))
    assert err is not None
    assert ctx is None
    assert err["data"]["reason"] == ReasonCode.PATH_UNSAFE


@pytest.mark.parametrize(
    ("stderr", "expected"),
    [
        ("fatal: a branch named 'feature/x' already exists", ReasonCode.BRANCH_EXISTS),
        (
            "error: pathspec 'missing' did not match any file(s)",
            ReasonCode.BRANCH_NOT_FOUND,
        ),
        (
            "Your local changes would be overwritten by checkout",
            ReasonCode.WORKTREE_DIRTY,
        ),
        ("fatal: 'bad name' is not a valid branch name", ReasonCode.INVALID_BRANCH),
        ("fatal: cannot switch", ReasonCode.GIT_ERROR),
    ],
)
def test_classify_switch_stderr(stderr: str, expected: str) -> None:
    assert _classify_switch_stderr(stderr) == expected


@pytest.mark.parametrize(
    ("stderr", "expected"),
    [
        ("pre-commit hook failed", ReasonCode.HOOK_REJECTED),
        ("Please tell me who you are", ReasonCode.IDENTITY_NOT_SET),
        ("error: nothing to revert", ReasonCode.NOTHING_TO_REVERT),
        ("CONFLICT (content): merge conflict", ReasonCode.REVERT_CONFLICT),
        ("Your local changes would be overwritten", ReasonCode.WORKTREE_DIRTY),
        ("fatal: revert failed", ReasonCode.GIT_ERROR),
    ],
)
def test_classify_revert_stderr(stderr: str, expected: str) -> None:
    assert _classify_revert_stderr(stderr) == expected
